const BUTTON_SIZE = {
  tiny: {
    minHeight: 24,
    borderRadius: 50,
    borderWidth: 0,
    iconWidth: 16,
    iconHeight: 16,
    textFontSize: 16,
  },
  '64': {
    minHeight: 64,
    minWidth: 64,
    borderRadius: 99,
    borderWidth: 0,
    iconWidth: 25.6,
    iconHeight: 25.6,
  },
  '32': {
    minHeight: 32,
    minWidth: 32,
    borderRadius: 99,
    borderWidth: 0,
    iconWidth: 7,
    iconHeight: 10,
  },
  '44': {
    minHeight: 44,
    minWidth: 32,
    borderRadius: 24,
    borderWidth: 0,
    iconWidth: 7,
    iconHeight: 10,
  },
  '80': {
    minHeight: 80,
    minWidth: 80,
    borderRadius: 99,
    borderWidth: 0,
    iconWidth: 18,
    iconHeight: 24,
  },
  small: {
    minHeight: 40,
    iconWidth: 20,
    iconHeight: 20,
    borderRadius: 24,
    borderWidth: 0,
    textFontSize: 16,
    textMarginHorizontal: 8,
  },
  medium: {
    minHeight: 48,
    borderRadius: 24,
    textFontSize: 16,
    iconWidth: 24,
    iconHeight: 24,
    textMarginHorizontal: 8,
    iconMarginHorizontal: 0,
  },
  large: {
    minHeight: 48,
    borderRadius: 24,
    borderWidth: 0,
    paddingHorizontal: 0,
    textFontSize: 16,
    iconWidth: 20,
    iconHeight: 20,
    justifyContent: 'space-between',
    iconMarginHorizontal: 0,
    textMarginHorizontal: 8,
  },
  '48': {
    minHeight: 48,
    borderRadius: 16,
    borderWidth: 0,
    paddingHorizontal: 0,
    textFontSize: 16,
    iconWidth: 24,
    iconHeight: 21,
    justifyContent: 'space-between',
    iconMarginHorizontal: 0,
    textMarginHorizontal: 8,
  },
  giant: {
    minHeight: 52,
    borderRadius: 24,
    borderWidth: 'border-width',
    textMarginHorizontal: 0,
    textFontSize: 16,
    iconWidth: 24,
    iconHeight: 24,
    paddingHorizontal: 24,
    justifyContent: 'space-between',
    iconMarginHorizontal: 0,
  },
};
export default BUTTON_SIZE;
