const TEXT_STYLE_VARIABLES = {
  'text-font-family': 'Celias-Light',
  'text-font-family-Overpass-Bold': 'Celias-Black',
  'text-font-family-Overpass-Italic': 'Celias-Italic',
  'text-font-family-SFProDisplay-Bold': 'SFProDisplay-Bold',
  'text-font-family-SFProDisplay-HeavyItalic': 'SFProDisplay-HeavyItalic',
  'text-font-family-Overpass-Regular': 'Celias',
  'text-font-family-Overpass-SemiBold': 'Celias-Bold',
  'text-font-family-Montserrat-Regular': 'Montserrat-Regular',
  'text-font-family-Overpass-ExtraBoldItalic': 'Celias-BlackItalic',
  'text-font-family-Roboto-BlackItalic': 'Roboto-BlackItalic',
  'text-font-family-SpaceMono-Regular': 'SpaceMono-Regular',
  'text-extra-1-font-size': 56,
  'text-extra-1-font-weight': '800',
  'text-extra-1-font-family': 'Roboto-BlackItalic',
  'text-roboto-1-font-size': 32,
  'text-roboto-1-font-weight': '900',
  'text-roboto-1-font-family': 'Roboto-BlackItalic',
  'text-extra-2-font-size': 56,
  'text-extra-2-font-weight': '800',
  'text-extra-2-font-family': 'SFProDisplay-HeavyItalic',
  'text-heading-1-font-size': 36,
  'text-heading-1-font-weight': '700',
  'text-heading-1-font-family': 'Celias-Bold',
  'text-title-1-font-size': 32,
  'text-title-1-font-weight': '700',
  'text-title-1-font-family': 'Celias-Bold',
  'text-title-2-font-size': 28,
  'text-title-2-font-weight': '700',
  'text-title-2-font-family': 'Celias-Bold',
  'text-title-3-font-size': 24,
  'text-title-3-font-weight': '700',
  'text-title-3-font-family': 'Celias-Bold',
  'text-title-4-font-size': 18,
  'text-title-4-font-weight': '700',
  'text-title-4-font-family': 'Celias-Bold',
  'text-body-1-font-size': 16,
  'text-body-1-font-weight': '400',
  'text-body-1-font-family': 'Celias-Bold',
  'text-call-out-font-size': 16,
  'text-call-out-font-weight': '600',
  'text-call-out-font-family': 'Celias-Bold',
  'text-headline-font-size': 16,
  'text-headline-font-weight': '600',
  'text-headline-font-family': 'Celias',
  'text-subhead-1-font-size': 14,
  'text-subhead-1-font-weight': '400',
  'text-subhead-1-font-family': 'Celias-Light',
  'text-footnote-font-size': 13,
  'text-footnote-font-weight': '400',
  'text-footnote-font-family': 'Celias',
  'text-caption-1-font-size': 12,
  'text-caption-1-font-weight': '400',
  'text-caption-1-font-family': 'Celias-Bold',
  'text-caption-2-font-size': 10,
  'text-caption-2-font-weight': '400',
  'text-caption-2-font-family': 'Celias-Bold',
  'text-label-font-size': 12,
  'text-label-font-weight': '800',
  'text-label-font-family': 'Celias-Bold',
  'text-h6-font-size': 12,
  'text-h6-font-weight': '700',
  'text-h6-font-family': 'SFProDisplay-Bold',
  'size-tiny': 24,
  'size-small': 32,
  'size-medium': 36,
  'size-large': 48,
  'size-giant': 56,
};

const TEXT_CATEGORIES = {
  h6: {
    fontSize: 'text-h6-font-size',
    fontFamily: 'text-h6-font-family',
  },
  roboto: {
    fontSize: 'text-roboto-1-font-size',
    fontFamily: 'text-roboto-1-font-family',
  },
  extra: {
    fontSize: 'text-extra-1-font-size',
    fontFamily: 'text-extra-1-font-family',
  },
  'extra-1': {
    fontSize: 'text-extra-2-font-size',
    fontFamily: 'SFProDisplay-HeavyItalic',
  },
  header: {
    fontSize: 'text-heading-1-font-size',
    fontFamily: 'text-heading-1-font-family',
  },
  title1: {
    fontSize: 'text-title-1-font-size',
    fontFamily: 'text-title-1-font-family',
  },
  title2: {
    fontSize: 'text-title-2-font-size',
    fontFamily: 'text-title-2-font-family',
  },
  title3: {
    fontSize: 'text-title-3-font-size',
    fontFamily: 'text-title-3-font-family',
  },
  title4: {
    fontSize: 'text-title-4-font-size',
    fontFamily: 'text-title-4-font-family',
  },
  body: {
    fontSize: 'text-body-1-font-size',
    fontFamily: 'text-body-1-font-family',
  },
  'call-out': {
    fontSize: 'text-call-out-font-size',
    fontFamily: 'text-call-out-font-family',
  },
  headline: {
    fontSize: 'text-headline-font-size',
    fontFamily: 'text-headline-font-family',
  },
  subhead: {
    fontSize: 'text-subhead-1-font-size',
    fontFamily: 'text-subhead-1-font-family',
  },
  footnote: {
    fontSize: 'text-footnote-font-size',
    fontFamily: 'text-footnote-font-family',
  },
  caption1: {
    fontSize: 'text-caption-1-font-size',
    fontFamily: 'text-caption-1-font-family',
  },
  caption2: {
    fontSize: 'text-caption-2-font-size',
    fontFamily: 'text-caption-2-font-family',
  },
  label: {
    fontSize: 'text-label-font-size',
    fontFamily: 'text-label-font-family',
  },
};

export {TEXT_STYLE_VARIABLES, TEXT_CATEGORIES};
