# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore")
    increment_build_number(xcodeproj: "/Users/alex/Dev/navcash/ios/navcash.xcodeproj")
    build_app(workspace: "navcash.xcworkspace", scheme: "navcash")
    upload_to_testflight
  end
end

lane :release do
  get_certificates           # invokes cert
  get_provisioning_profile 
  build_app(scheme: "navcash",
            workspace: "navcash.xcworkspace",
            include_bitcode: true)
  upload_to_app_store                  # upload your app to App Store Connect
  slack(message: "Successfully uploaded a new App Store build")
end
